function [  number_of_samples, ...
            d2, ...
            S2, ...
            d3, ...
            theta3, ...
            S3, ...            
            execution_time] = read_output(file_path)

file_string = fileread(file_path);

number_of_samples = read_key(file_string, 'number_of_samples', 'scalar');
d2 = read_key(file_string, 'd2', 'array');
S2 = read_key(file_string, 'S2', 'array');
d3 = read_key(file_string, 'd3', 'array');
theta3 = read_key(file_string, 'theta3', 'array');
S3 = read_key(file_string, 'S3', 'array');
execution_time = read_key(file_string, 'execution_time', 'scalar');

end