function [  output_generation_path, ...
            number_of_samples, ...
            d, ...
            number_of_cells_x, ...
            number_of_cells_y, ...
            number_of_cells_z, ...
            output_diffusion_path] = read_input(file_path)

file_string = fileread(file_path);

output_generation_path = read_key(file_string, 'output_generation_path', 'string');
number_of_samples = read_key(file_string, 'number_of_samples', 'scalar');
d = read_key(file_string, 'd', 'array');
number_of_cells_x = read_key(file_string, 'number_of_cells_x', 'scalar');
number_of_cells_y = read_key(file_string, 'number_of_cells_y', 'scalar');
number_of_cells_z = read_key(file_string, 'number_of_cells_z', 'scalar');
output_diffusion_path = read_key(file_string, 'output_diffusion_path', 'string');

end